absl_py:
  - 0.8.1.*
astunparse:
  - 1.6
autoconf:
  - 2.69
automake:
  - 1.16
bazel:
  - 2.0.*
bazel3:
  - 3.*
boost:
  - 1.67.0
c_compiler_version:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
cffi:
  - 1.14.*
click:
  - 7.0.*
cloudpickle:
  - 1.3.*
cmake:
  - 3.14.*
coverage:
  - 4.*
cudatoolkit:
  - 10.2.*
cudnn:
  - 7.6.5.*
cxx_compiler_version:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
cxxfilt:
  - 0.2.*
cymem:
  - 2.0.*
cython:
  - 0.29
cython_blis:
  - 0.4.*
dm_tree:
  - 0.1.*
eigen:
  - 3.3.7
ffmpeg:
  - 4.2
freetype:
  - 2
fortran_compiler_version:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
future:
  - 0.18.*
gast:
  - 0.3.3
google_pasta:
  - 0.1.8
graphsurgeon:
  - 0.4.1
grpcio:
  - 1.16.1
harfbuzz:
  - 1.8
# Note: hdf5 version must be compatible with h5py
hdf5:
  - 1.10.4
hypothesis:
  - 5.*
h5py:
  - 2.10.0
jasper:
  - 2.0.14
joblib:
  - 0.13.2
jpeg:
  - 9b
jpegturbo:
  - 2.0.5
keras_applications:
  - 1.0.8
keras_preprocessing:
  - 1.1.*
leveldb:
  - 1.20.*
libevent:
  - 2.1.*
libgfortran:
  - 7.2.*                      # [x86_64]
  - 7.3.*                      # [ppc64le]
libogg:
  - 1.3.*
libpng:
  - 1.6
libtiff:
  - 4.1
libtool:
  - 2.4.6
lmdb:
  - 0.9.22.*
magma:
  - 2.5.3.*
make:
  - 4.2.1
markdown:
  - 3.1
mock:
  - 3.*
murmurhash:
  - 1.0.*
nasm:                          # [x86_64]
  - 2.13.03                    # [x86_64]
networkx:
  - 2.3.*
ninja:
  - 1.9.*
nccl:
  - 2.7.*
numactl:
  - 2.0.*
numba:
  - 0.47.*
numpy:
  - 1.17.*
onnx:
  - 1.6.*
openblas:
  - 0.3.6.*
opencv:
  - 3.4.10.*
openjdk:
  - 8.0.152 # [x86_64]
  - 1.8.0   # [ppc64le]
openmpi:
  - 3.1.3
opt_einsum:
  - 3.1.0
pillow:
  - 7.1.*
pip:
  - 19*
pkg_config:
  - 0.29.2
plac:
  - 0.9.6
preshed:
  - 3.0.*
protobuf:
  - 3.9.*
psutil:
  - 5
pytest:
  - 5.*
python:
  - 3.6
  - 3.7
python_lmdb:
  - 0.98.*
pytorch:
  - 1.6.*
pyyaml:
  - 5.*
requests:
  - 2.22
regex:
  - 2020.6.*
rust_nightly:
  - 1.48.0
scikit_image:
  - 0.16
scikit_learn:
  - 0.22
scipy:
  - 1.4.*
sentencepiece:
  - 0.1.86
setuptools:
  - 41.*
setuptools_rust:
  - 0.10.6
six:
  - 1.13.0
srsly:
  - 0.2.0
tabulate:
  - 0.8.*
tensorboard:
  - 2.3.*
tensorboard_plugin_wit:
  - 1.6
tensorflow:
  - 2.3.*
tensorrt:
  - 7.0.*
termcolor:
  - 1.1.0
thinc:
  - 7.1.1
tokenizers:
  - 0.7.0
torchtext:
  - 0.7.*
torchvision:
  - 0.7.*
tqdm:
  - 4.36.*
typing:
  - 3.7.4.1
uff:
  - 0.6.5
unzip:
  - 6.0
wasabi:
  - 0.6.0
werkzeug:
  - 0.16.0
wheel:
  - 0.33*
wrapt:
  - 1.11
zlib:
  - 1.2.11
