name: Open-CE Environment Tests

on:
  push:
    branches:
      - 'main'        # matches the main branch
      - 'open-ce-r*'  # matches every release branch
  pull_request:
    branches:
      - 'main'        # matches the main branch
      - 'open-ce-r*'  # matches every release branch

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: 3.8
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y pylint=2.6.0 \
                           conda-build
          pip install yamllint==1.24.2
      - name: Validate config files
        shell: bash -l {0}
        run: |
          # Use yamllint to check the actual yaml files.
          yamllint .github/actions/*/*.yml .github/workflows/*.yml
          yamllint ./envs/conda_build_config.yaml
          pip install git+https://github.com/open-ce/open-ce-builder.git@open-ce-r1.3
          # Use the conda_build api to lint the env files since they use jinja.
          open-ce validate env envs/*-env.yaml
          # Validate conda_build_config for the main open-ce env file.
          open-ce validate config --conda_build_config \
                                            ./envs/conda_build_config.yaml \
                                            ./envs/*-env.yaml \
                                            --python_versions 3.7,3.8,3.9 \
                                            --build_types cuda,cpu \
                                            --mpi_types openmpi,system
