name: Open-CE XGBoost Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        architecture: [x86, ppc64le]

    steps:
      - uses: actions/checkout@v2
      - uses: uraimo/run-on-arch-action@v2.0.1
        with:
          arch: ${{ matrix.architecture }}
          distro: ubuntu18.04
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install -y conda-build
      - name: Build XGBoost
        shell: bash -l {0}
        # yamllint disable rule:line-length
        run: |
          ./open-ce/open-ce build env https://raw.githubusercontent.com/open-ce/open-ce-environments/main/envs/xgboost-env.yaml \
                            --python_versions ${{ matrix.python-version }} \
                            --build_types cpu
        # yamllint enable rule:line-length
